const DAYURL='./data/days.csv',PARTURL='./data/participants.csv',STARURL='./data/stars.csv';let days=[],parts=[],stars=[];let today=new Date('2026-09-15T00:00:00+09:00');
function localDate(s){return new Date(s+'T00:00:00+09:00')}
function csv(t){const lines=t.trim().split(/\r?\n/);const keys=lines.shift().split(',');return lines.map(l=>{const v=l.split(',');return Object.fromEntries(keys.map((k,i)=>[k,v[i]??'']))})}
async function load(){const [d,p,s]=await Promise.all([fetch(DAYURL).then(r=>r.text()),fetch(PARTURL).then(r=>r.text()),fetch(STARURL).then(r=>r.text())]);days=JSON.parse(localStorage.getItem('aki-days')||'null')||csv(d);parts=JSON.parse(localStorage.getItem('aki-parts')||'null')||csv(p);stars=JSON.parse(localStorage.getItem('aki-stars')||'null')||csv(s).map(x=>({...x,points:+x.points}));render()}
function activeIndex(){return Math.max(0,Math.min(days.length-1,Math.round((today-localDate('2026-09-13'))/86400000)))}
function render(){const belt=document.querySelector('#belt');belt.innerHTML='';days.forEach((d,i)=>{const e=document.createElement('article');e.className='day';e.dataset.i=i;e.innerHTML=`<div class="daynum">DAY ${d.day}</div><div class="num">${d.date.slice(5).replace('-','.')}</div><div class="date">${localDate(d.date).toLocaleDateString('ja-JP',{weekday:'short'})}</div><div class="theme">${d.theme||'テーマ未定'}</div><div class="winner">${d.winner?'★ '+d.winner:'勝者未定'}</div>${i===activeIndex()?'<span class="badge">TODAY</span>':''}`;belt.append(e)});setupBelt();renderScores()}
function setupBelt(){const belt=document.querySelector('#belt');const cards=[...belt.children];const focus=()=>{const mid=belt.scrollLeft+belt.clientWidth/2;let best=0,dist=Infinity;cards.forEach((c,i)=>{const x=c.offsetLeft+c.offsetWidth/2,d=Math.abs(x-mid);if(d<dist){dist=d;best=i}});cards.forEach((c,i)=>{c.classList.toggle('active',i===best);c.classList.toggle('near',Math.abs(i-best)===1);c.classList.toggle('left',i<best-1);c.classList.toggle('right',i>best+1);if(i>=best-1&&i<=best+1)c.classList.remove('left','right')})};belt.addEventListener('scroll',()=>requestAnimationFrame(focus),{passive:true});setTimeout(()=>{cards[activeIndex()]?.scrollIntoView({behavior:'instant',inline:'center'});focus()},30)}
function renderScores(){const box=document.querySelector('#score');box.innerHTML='';const totals=parts.map(p=>{const mine=stars.filter(s=>s.participant_id===p.id&&s.points>0);return {...p,total:mine.reduce((a,s)=>a+s.points,0)}}).sort((a,b)=>b.total-a.total);totals.forEach(p=>{const el=document.createElement('div');el.className='person';const ss=days.map(d=>{const ok=localDate(d.date)>=localDate(p.joined)&&stars.some(s=>s.date===d.date&&s.participant_id===p.id&&s.points>0);return `<button class="star ${ok?'on':''}" data-id="${p.id}" data-date="${d.date}">★</button>`}).join('');el.innerHTML=`<div class="top"><span class="name">${p.name}</span><strong class="total">${p.total}点</strong></div><div class="stars">${ss}</div>`;box.append(el)});box.querySelectorAll('.star').forEach(b=>b.onclick=()=>toggleStar(b.dataset.id,b.dataset.date))}
function toggleStar(id,date){const idx=stars.findIndex(s=>s.participant_id===id&&s.date===date);if(idx>=0)stars[idx].points=stars[idx].points?0:1;else stars.push({participant_id:id,date,points:1});saveLocal();renderScores()}
function saveLocal(){localStorage.setItem('aki-days',JSON.stringify(days));localStorage.setItem('aki-parts',JSON.stringify(parts));localStorage.setItem('aki-stars',JSON.stringify(stars))}
function editor(){const modal=document.querySelector('#editor');modal.hidden=false;document.querySelector('#login').hidden=false;document.querySelector('#editForm').hidden=true;document.querySelector('#password').value=''}
function buildEditor(){document.querySelector('#login').hidden=true;document.querySelector('#editForm').hidden=false;document.querySelector('#dayEdit').innerHTML=days.map((d,i)=>`<div class="edit-row"><span class="small">${d.day}</span><input data-day="${i}" data-key="date" value="${d.date}" type="date"><input data-day="${i}" data-key="theme" value="${d.theme||''}" placeholder="テーマ"><input data-day="${i}" data-key="winner" value="${d.winner||''}" placeholder="勝者"></div>`).join('');document.querySelector('#participantEdit').innerHTML=parts.map((p,i)=>`<div class="participant-row"><span class="small">${p.id}</span><input data-part="${i}" data-key="name" value="${p.name}" placeholder="名前"><input data-part="${i}" data-key="joined" value="${p.joined}" type="date"></div>`).join('')}
function applyEditor(){document.querySelectorAll('[data-day]').forEach(x=>days[+x.dataset.day][x.dataset.key]=x.value);document.querySelectorAll('[data-part]').forEach(x=>parts[+x.dataset.part][x.dataset.key]=x.value);saveLocal();render();alert('保存しました（この端末のみ）')}
function download(name,text){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
function csvOut(rows,keys){return [keys.join(','),...rows.map(r=>keys.map(k=>String(r[k]??'').replaceAll(',','，')).join(','))].join('\n')+'\n'}
document.querySelector('#editOpen').onclick=editor;document.querySelector('#editClose').onclick=()=>document.querySelector('#editor').hidden=true;document.querySelector('#loginBtn').onclick=()=>document.querySelector('#password').value==='aki'?buildEditor():(document.querySelector('#loginError').textContent='パスワードが違います');document.querySelector('#saveLocal').onclick=applyEditor;document.querySelector('#exportDays').onclick=()=>download('days.csv',csvOut(days,['day','date','theme','winner']));document.querySelector('#exportParticipants').onclick=()=>download('participants.csv',csvOut(parts,['id','name','joined']));document.querySelector('#exportStars').onclick=()=>download('stars.csv',csvOut(stars,['date','participant_id','points']));
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');load();