const DAYURL='./data/days.csv',PARTURL='./data/participants.csv',STARURL='./data/stars.csv';const FEEDBACK_API='https://feedback-api.vercel.app/feedback';const DAYS_DATA_VERSION='2026-09-16-1';let days=[],parts=[],stars=[];let today=new Date('2026-09-15T00:00:00+09:00');let activeDay=0;let dragging=false,startY=0,startX=0,lastY=0,lastTime=0,dragDistance=0;
function localDate(s){return new Date(s+'T00:00:00+09:00')}
function csv(t){const lines=t.trim().split(/\r?\n/);const keys=lines.shift().split(',');return lines.map(l=>{const v=l.split(',');return Object.fromEntries(keys.map((k,i)=>[k,v[i]??'']))})}
async function load(){const [d,p,s]=await Promise.all([fetch(DAYURL).then(r=>r.text()),fetch(PARTURL).then(r=>r.text()),fetch(STARURL).then(r=>r.text())]);const savedDays=JSON.parse(localStorage.getItem('aki-days')||'null');days=savedDays&&localStorage.getItem('aki-days-version')===DAYS_DATA_VERSION?savedDays:csv(d);parts=JSON.parse(localStorage.getItem('aki-parts')||'null')||csv(p);stars=JSON.parse(localStorage.getItem('aki-stars')||'null')||csv(s).map(x=>({...x,points:+x.points}));activeDay=activeIndex();render()}
function activeIndex(){return Math.max(0,Math.min(days.length-1,Math.round((today-localDate('2026-09-13'))/86400000)))}
function render(){const belt=document.querySelector('#belt');belt.innerHTML='';days.forEach((d,i)=>{const dt=localDate(d.date);const weekday=dt.toLocaleDateString('ja-JP',{weekday:'short'});const e=document.createElement('article');e.className='day';e.dataset.i=i;e.innerHTML=`<div class="daynum">DAY ${d.day}</div><div class="num">${d.date.slice(5).replace('-','.')}</div><div class="date"><span class="date-weekday">${weekday}</span></div><div class="theme">${d.theme||'テーマ未定'}</div><div class="winner">${d.winner?'★ '+d.winner:'勝者未定'}</div>${i===activeIndex()?'<span class="badge">TODAY</span>':''}`;belt.append(e)});setupBelt();renderScores()}
function setupBelt(){const belt=document.querySelector('#belt');const cards=[...belt.children];belt.scrollTop=0;belt.scrollLeft=0;cards.forEach((c,i)=>c.classList.toggle('active',i===activeDay));setTimeout(()=>cards[activeDay]?.scrollIntoView({behavior:'instant',block:'center'}),20);belt.onpointerdown=onPointerDown;belt.onpointermove=onPointerMove;belt.onpointerup=onPointerUp;belt.onpointercancel=cancelPointer;belt.onpointerleave=e=>{if(dragging&&e.pointerType==='mouse')finishPointer(e)}}
function onPointerDown(e){if(e.button!==undefined&&e.button!==0)return;dragging=true;startY=lastY=e.clientY;startX=e.clientX;lastTime=performance.now();dragDistance=0;document.body.classList.add('dragging');e.currentTarget.setPointerCapture?.(e.pointerId)}
function onPointerMove(e){if(!dragging)return;const dy=e.clientY-startY;const dx=e.clientX-startX;dragDistance=Math.max(dragDistance,Math.abs(dy));lastY=e.clientY;lastTime=performance.now();if(Math.abs(dy)>Math.abs(dx)&&Math.abs(dy)>4)e.preventDefault()}
function onPointerUp(e){if(!dragging)return;finishPointer(e)}
function finishPointer(e){const dy=e.clientY-startY;const threshold=55;let next=activeDay;if(Math.abs(dy)>=threshold)next=dy<0?Math.min(days.length-1,activeDay+1):Math.max(0,activeDay-1);activeDay=next;document.body.classList.remove('dragging');dragging=false;const cards=[...document.querySelectorAll('.day')];cards.forEach((c,i)=>c.classList.toggle('active',i===activeDay));cards[activeDay]?.scrollIntoView({behavior:'smooth',block:'center'})}
function cancelPointer(){dragging=false;document.body.classList.remove('dragging')}
function renderScores(){const box=document.querySelector('#score');box.innerHTML='';const totals=parts.map(p=>{const mine=stars.filter(s=>s.participant_id===p.id&&s.points>0);return {...p,total:mine.reduce((a,s)=>a+s.points,0)}}).sort((a,b)=>b.total-a.total);totals.forEach(p=>{const el=document.createElement('div');el.className='person';const ss=days.map(d=>{const ok=localDate(d.date)>=localDate(p.joined)&&stars.some(s=>s.date===d.date&&s.participant_id===p.id&&s.points>0);return `<button class="star ${ok?'on':''}" data-id="${p.id}" data-date="${d.date}">★</button>`}).join('');el.innerHTML=`<div class="top"><span class="name">${p.name}</span><strong class="total">${p.total}点</strong></div><div class="stars">${ss}</div>`;box.append(el)});box.querySelectorAll('.star').forEach(b=>b.onclick=()=>toggleStar(b.dataset.id,b.dataset.date))}
function toggleStar(id,date){const idx=stars.findIndex(s=>s.participant_id===id&&s.date===date);if(idx>=0)stars[idx].points=stars[idx].points?0:1;else stars.push({participant_id:id,date,points:1});saveLocal();renderScores()}
function saveLocal(){localStorage.setItem('aki-days',JSON.stringify(days));localStorage.setItem('aki-days-version',DAYS_DATA_VERSION);localStorage.setItem('aki-parts',JSON.stringify(parts));localStorage.setItem('aki-stars',JSON.stringify(stars))}
async function openFeedback(){const d=days[activeDay]||{};const message=window.prompt(`DAY ${d.day||''} / ${d.theme||'テーマ未定'}\n\nデザインのダメだしを入力してください`);if(!message?.trim())return;try{const res=await fetch(FEEDBACK_API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({day:Number(d.day)||activeDay+1,theme:d.theme||'',category:'デザイン',message:message.trim()})});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||`HTTP ${res.status}`);alert(`受け付けました\nIssue #${data.number||''}`)}catch(err){alert(`送信できませんでした\n${err.message}\n\nVercel APIのDeployとGITHUB_TOKEN設定を確認してください`)}}
function editor(){const modal=document.querySelector('#editor');modal.hidden=false;document.querySelector('#login').hidden=false;document.querySelector('#editForm').hidden=true;document.querySelector('#password').value='';document.querySelector('#participantError').textContent=''}
function buildEditor(){document.querySelector('#login').hidden=true;document.querySelector('#editForm').hidden=false;renderEditor()}
function renderEditor(){document.querySelector('#dayEdit').innerHTML=days.map((d,i)=>`<div class="edit-row"><span class="small">${d.day}</span><input data-day="${i}" data-key="date" value="${d.date}" type="date"><input data-day="${i}" data-key="theme" value="${d.theme||''}" placeholder="テーマ"><input data-day="${i}" data-key="winner" value="${d.winner||''}" placeholder="勝者"></div>`).join('');document.querySelector('#participantEdit').innerHTML=parts.map((p,i)=>`<div class="participant-row"><span class="small">${p.id}</span><input data-part="${i}" data-key="name" value="${p.name}" placeholder="名前"><input data-part="${i}" data-key="joined" value="${p.joined}" type="date"></div>`).join('')}
function addParticipant(){const name=document.querySelector('#newParticipantName').value.trim();const joined=document.querySelector('#newParticipantJoined').value||'2026-09-15';const error=document.querySelector('#participantError');if(!name){error.textContent='参加者名を入力してください';return}if(parts.some(p=>p.name.trim()===name)){error.textContent='同じ名前の参加者がすでに登録されています';return}const id=String(parts.reduce((m,p)=>Math.max(m,Number(p.id)||0),0)+1);parts.push({id,name,joined});document.querySelector('#newParticipantName').value='';document.querySelector('#newParticipantJoined').value='';error.textContent=`${name} を登録しました`;renderEditor()}
function applyEditor(){document.querySelectorAll('[data-day]').forEach(x=>days[+x.dataset.day][x.dataset.key]=x.value);document.querySelectorAll('[data-part]').forEach(x=>parts[+x.dataset.part][x.dataset.key]=x.value);saveLocal();render();alert('保存しました（この端末のみ）')}
function download(name,text){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
function csvOut(rows,keys){return [keys.join(','),...rows.map(r=>keys.map(k=>String(r[k]??'').replaceAll(',','，')).join(','))].join('\n')+'\n'}
document.querySelector('#editOpen').onclick=editor;document.querySelector('#feedbackOpen').onclick=openFeedback;document.querySelector('#editClose').onclick=()=>document.querySelector('#editor').hidden=true;document.querySelector('#loginBtn').onclick=()=>document.querySelector('#password').value==='aki'?buildEditor():(document.querySelector('#loginError').textContent='パスワードが違います');document.querySelector('#addParticipant').onclick=addParticipant;document.querySelector('#saveLocal').onclick=applyEditor;document.querySelector('#exportDays').onclick=()=>download('days.csv',csvOut(days,['day','date','theme','winner']));document.querySelector('#exportParticipants').onclick=()=>download('participants.csv',csvOut(parts,['id','name','joined']));document.querySelector('#exportStars').onclick=()=>download('stars.csv',csvOut(stars,['date','participant_id','points']));
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');load();