const DAYURL='./data/days.csv',PARTURL='./data/participants.csv',STARURL='./data/stars.csv';let days=[],parts=[],stars=[];let today=new Date('2026-09-15T00:00:00+09:00');
function localDate(s){return new Date(s+'T00:00:00+09:00')}
function csv(t){const lines=t.trim().split(/\r?\n/);const keys=lines.shift().split(',');return lines.map(l=>{const v=l.split(',');return Object.fromEntries(keys.map((k,i)=>[k,v[i]??'']))})}
async function load(){const [d,p,s]=await Promise.all([fetch(DAYURL).then(r=>r.text()),fetch(PARTURL).then(r=>r.text()),fetch(STARURL).then(r=>r.text())]);days=csv(d);parts=csv(p);stars=csv(s).map(x=>({...x,points:+x.points}));render()}
function activeIndex(){return Math.max(0,Math.min(days.length-1,Math.round((today-localDate('2026-09-13'))/86400000)))}
function render(){const belt=document.querySelector('#belt');belt.innerHTML='';days.forEach((d,i)=>{const e=document.createElement('article');e.className='day';e.dataset.i=i;e.innerHTML=`<div class="daynum">DAY ${d.day}</div><div class="num">${d.date.slice(5).replace('-','.')}</div><div class="date">${localDate(d.date).toLocaleDateString('ja-JP',{weekday:'short'})}</div><div class="theme">${d.theme||'テーマ未定'}</div><div class="winner">${d.winner?'★ '+d.winner:'勝者未定'}</div>${i===activeIndex()?'<span class="badge">TODAY</span>':''}`;belt.append(e)});setupBelt();renderScores()}
function setupBelt(){const belt=document.querySelector('#belt');const cards=[...belt.children];const focus=()=>{const mid=belt.scrollLeft+belt.clientWidth/2;let best=0,dist=Infinity;cards.forEach((c,i)=>{const x=c.offsetLeft+c.offsetWidth/2,d=Math.abs(x-mid);if(d<dist){dist=d;best=i}});cards.forEach((c,i)=>{c.classList.toggle('active',i===best);c.classList.toggle('near',Math.abs(i-best)===1);c.classList.toggle('left',i<best-1);c.classList.toggle('right',i>best+1);if(i>=best-1&&i<=best+1)c.classList.remove('left','right')})};belt.addEventListener('scroll',()=>requestAnimationFrame(focus),{passive:true});setTimeout(()=>{cards[activeIndex()]?.scrollIntoView({behavior:'instant',inline:'center'});focus()},30)}
function renderScores(){const box=document.querySelector('#score');box.innerHTML='';const totals=parts.map(p=>{const mine=stars.filter(s=>s.participant_id===p.id&&s.points>0);return {...p,total:mine.reduce((a,s)=>a+s.points,0)}}).sort((a,b)=>b.total-a.total);totals.forEach(p=>{const el=document.createElement('div');el.className='person';const ss=days.map(d=>{const ok=localDate(d.date)>=localDate(p.joined)&&stars.some(s=>s.date===d.date&&s.participant_id===p.id&&s.points>0);return `<button class="star ${ok?'on':''}" data-id="${p.id}" data-date="${d.date}">★</button>`}).join('');el.innerHTML=`<div class="top"><span class="name">${p.name}</span><strong class="total">${p.total}点</strong></div><div class="stars">${ss}</div>`;box.append(el)});box.querySelectorAll('.star').forEach(b=>b.onclick=()=>toggleStar(b.dataset.id,b.dataset.date))}
function toggleStar(id,date){const idx=stars.findIndex(s=>s.participant_id===id&&s.date===date);if(idx>=0)stars[idx].points=stars[idx].points?0:1;else stars.push({participant_id:id,date,points:1});renderScores()}
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');load();